language: cpp

notifications:
  irc: "chat.freenode.net##crow"

compiler:
  - gcc
  #- clang

before_script:
  - sudo pip install cpp-coveralls
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -qq libboost1.55-all-dev
  - sudo apt-get install -qq g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir build
  - cd build
  - sudo apt-get install cmake
  - cmake --version
  - cmake ..

script: make && ctest

after_success:
  - cd ..
  - coveralls --gcov gcov-4.8 -i include --gcov-options '\-lp'
